"""empty message

Revision ID: 03511d7d7521
Revises: 2be94cbd1c62
Create Date: 2020-09-09 09:44:51.164971

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '03511d7d7521'
down_revision = '2be94cbd1c62'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Artist', sa.Column('seeking_venue', sa.Boolean(), nullable=True))
    op.drop_column('Artist', 'seek_venue')
    op.add_column('Venue', sa.Column('seeking_talent', sa.Boolean(), nullable=True))
    op.drop_column('Venue', 'seek_talent')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Venue', sa.Column('seek_talent', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.drop_column('Venue', 'seeking_talent')
    op.add_column('Artist', sa.Column('seek_venue', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.drop_column('Artist', 'seeking_venue')
    # ### end Alembic commands ###
